/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppAdjustersRouteImport } from './routes/_authenticated/app.adjusters'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppCalendarRouteImport } from './routes/_authenticated/app.calendar'
import { Route as AuthenticatedAppClaimsRouteImport } from './routes/_authenticated/app.claims'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated/app.customers'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/app.documents'
import { Route as AuthenticatedAppInterviewRouteImport } from './routes/_authenticated/app.interview'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppSupplementsRouteImport } from './routes/_authenticated/app.supplements'
import { Route as ApiAiExecutiveSummaryRouteImport } from './routes/api/ai.executive-summary'
import { Route as ApiAiInterviewSummaryRouteImport } from './routes/api/ai.interview-summary'
import { Route as ApiAiSupplementGenerateRouteImport } from './routes/api/ai.supplement-generate'
import { Route as AuthenticatedAppClaimsClaimIdRouteImport } from './routes/_authenticated/app.claims.$claimId'
import { Route as AuthenticatedAppSupplementsSupplementIdRouteImport } from './routes/_authenticated/app.supplements.$supplementId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppAdjustersRoute =
  AuthenticatedAppAdjustersRouteImport.update({
    id: '/adjusters',
    path: '/adjusters',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCalendarRoute =
  AuthenticatedAppCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClaimsRoute = AuthenticatedAppClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInterviewRoute =
  AuthenticatedAppInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSupplementsRoute =
  AuthenticatedAppSupplementsRouteImport.update({
    id: '/supplements',
    path: '/supplements',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiAiExecutiveSummaryRoute = ApiAiExecutiveSummaryRouteImport.update({
  id: '/api/ai/executive-summary',
  path: '/api/ai/executive-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiInterviewSummaryRoute = ApiAiInterviewSummaryRouteImport.update({
  id: '/api/ai/interview-summary',
  path: '/api/ai/interview-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSupplementGenerateRoute = ApiAiSupplementGenerateRouteImport.update({
  id: '/api/ai/supplement-generate',
  path: '/api/ai/supplement-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppClaimsClaimIdRoute =
  AuthenticatedAppClaimsClaimIdRouteImport.update({
    id: '/$claimId',
    path: '/$claimId',
    getParentRoute: () => AuthenticatedAppClaimsRoute,
  } as any)
const AuthenticatedAppSupplementsSupplementIdRoute =
  AuthenticatedAppSupplementsSupplementIdRouteImport.update({
    id: '/$supplementId',
    path: '/$supplementId',
    getParentRoute: () => AuthenticatedAppSupplementsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/adjusters': typeof AuthenticatedAppAdjustersRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/claims': typeof AuthenticatedAppClaimsRouteWithChildren
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/interview': typeof AuthenticatedAppInterviewRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/supplements': typeof AuthenticatedAppSupplementsRouteWithChildren
  '/api/ai/executive-summary': typeof ApiAiExecutiveSummaryRoute
  '/api/ai/interview-summary': typeof ApiAiInterviewSummaryRoute
  '/api/ai/supplement-generate': typeof ApiAiSupplementGenerateRoute
  '/app/claims/$claimId': typeof AuthenticatedAppClaimsClaimIdRoute
  '/app/supplements/$supplementId': typeof AuthenticatedAppSupplementsSupplementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/adjusters': typeof AuthenticatedAppAdjustersRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/claims': typeof AuthenticatedAppClaimsRouteWithChildren
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/interview': typeof AuthenticatedAppInterviewRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/supplements': typeof AuthenticatedAppSupplementsRouteWithChildren
  '/api/ai/executive-summary': typeof ApiAiExecutiveSummaryRoute
  '/api/ai/interview-summary': typeof ApiAiInterviewSummaryRoute
  '/api/ai/supplement-generate': typeof ApiAiSupplementGenerateRoute
  '/app/claims/$claimId': typeof AuthenticatedAppClaimsClaimIdRoute
  '/app/supplements/$supplementId': typeof AuthenticatedAppSupplementsSupplementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/app/adjusters': typeof AuthenticatedAppAdjustersRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/_authenticated/app/claims': typeof AuthenticatedAppClaimsRouteWithChildren
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRoute
  '/_authenticated/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/app/interview': typeof AuthenticatedAppInterviewRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/supplements': typeof AuthenticatedAppSupplementsRouteWithChildren
  '/api/ai/executive-summary': typeof ApiAiExecutiveSummaryRoute
  '/api/ai/interview-summary': typeof ApiAiInterviewSummaryRoute
  '/api/ai/supplement-generate': typeof ApiAiSupplementGenerateRoute
  '/_authenticated/app/claims/$claimId': typeof AuthenticatedAppClaimsClaimIdRoute
  '/_authenticated/app/supplements/$supplementId': typeof AuthenticatedAppSupplementsSupplementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/sitemap.xml'
    | '/app'
    | '/api/chat'
    | '/app/adjusters'
    | '/app/admin'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/claims'
    | '/app/customers'
    | '/app/documents'
    | '/app/interview'
    | '/app/notifications'
    | '/app/settings'
    | '/app/supplements'
    | '/api/ai/executive-summary'
    | '/api/ai/interview-summary'
    | '/api/ai/supplement-generate'
    | '/app/claims/$claimId'
    | '/app/supplements/$supplementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/sitemap.xml'
    | '/app'
    | '/api/chat'
    | '/app/adjusters'
    | '/app/admin'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/claims'
    | '/app/customers'
    | '/app/documents'
    | '/app/interview'
    | '/app/notifications'
    | '/app/settings'
    | '/app/supplements'
    | '/api/ai/executive-summary'
    | '/api/ai/interview-summary'
    | '/api/ai/supplement-generate'
    | '/app/claims/$claimId'
    | '/app/supplements/$supplementId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/api/chat'
    | '/_authenticated/app/adjusters'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/calendar'
    | '/_authenticated/app/claims'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/documents'
    | '/_authenticated/app/interview'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/supplements'
    | '/api/ai/executive-summary'
    | '/api/ai/interview-summary'
    | '/api/ai/supplement-generate'
    | '/_authenticated/app/claims/$claimId'
    | '/_authenticated/app/supplements/$supplementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAiExecutiveSummaryRoute: typeof ApiAiExecutiveSummaryRoute
  ApiAiInterviewSummaryRoute: typeof ApiAiInterviewSummaryRoute
  ApiAiSupplementGenerateRoute: typeof ApiAiSupplementGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/adjusters': {
      id: '/_authenticated/app/adjusters'
      path: '/adjusters'
      fullPath: '/app/adjusters'
      preLoaderRoute: typeof AuthenticatedAppAdjustersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calendar': {
      id: '/_authenticated/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AuthenticatedAppCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/claims': {
      id: '/_authenticated/app/claims'
      path: '/claims'
      fullPath: '/app/claims'
      preLoaderRoute: typeof AuthenticatedAppClaimsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents': {
      id: '/_authenticated/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/interview': {
      id: '/_authenticated/app/interview'
      path: '/interview'
      fullPath: '/app/interview'
      preLoaderRoute: typeof AuthenticatedAppInterviewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/supplements': {
      id: '/_authenticated/app/supplements'
      path: '/supplements'
      fullPath: '/app/supplements'
      preLoaderRoute: typeof AuthenticatedAppSupplementsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/ai/executive-summary': {
      id: '/api/ai/executive-summary'
      path: '/api/ai/executive-summary'
      fullPath: '/api/ai/executive-summary'
      preLoaderRoute: typeof ApiAiExecutiveSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/interview-summary': {
      id: '/api/ai/interview-summary'
      path: '/api/ai/interview-summary'
      fullPath: '/api/ai/interview-summary'
      preLoaderRoute: typeof ApiAiInterviewSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/supplement-generate': {
      id: '/api/ai/supplement-generate'
      path: '/api/ai/supplement-generate'
      fullPath: '/api/ai/supplement-generate'
      preLoaderRoute: typeof ApiAiSupplementGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/claims/$claimId': {
      id: '/_authenticated/app/claims/$claimId'
      path: '/$claimId'
      fullPath: '/app/claims/$claimId'
      preLoaderRoute: typeof AuthenticatedAppClaimsClaimIdRouteImport
      parentRoute: typeof AuthenticatedAppClaimsRoute
    }
    '/_authenticated/app/supplements/$supplementId': {
      id: '/_authenticated/app/supplements/$supplementId'
      path: '/$supplementId'
      fullPath: '/app/supplements/$supplementId'
      preLoaderRoute: typeof AuthenticatedAppSupplementsSupplementIdRouteImport
      parentRoute: typeof AuthenticatedAppSupplementsRoute
    }
  }
}

interface AuthenticatedAppClaimsRouteChildren {
  AuthenticatedAppClaimsClaimIdRoute: typeof AuthenticatedAppClaimsClaimIdRoute
}

const AuthenticatedAppClaimsRouteChildren: AuthenticatedAppClaimsRouteChildren =
  {
    AuthenticatedAppClaimsClaimIdRoute: AuthenticatedAppClaimsClaimIdRoute,
  }

const AuthenticatedAppClaimsRouteWithChildren =
  AuthenticatedAppClaimsRoute._addFileChildren(
    AuthenticatedAppClaimsRouteChildren,
  )

interface AuthenticatedAppSupplementsRouteChildren {
  AuthenticatedAppSupplementsSupplementIdRoute: typeof AuthenticatedAppSupplementsSupplementIdRoute
}

const AuthenticatedAppSupplementsRouteChildren: AuthenticatedAppSupplementsRouteChildren =
  {
    AuthenticatedAppSupplementsSupplementIdRoute:
      AuthenticatedAppSupplementsSupplementIdRoute,
  }

const AuthenticatedAppSupplementsRouteWithChildren =
  AuthenticatedAppSupplementsRoute._addFileChildren(
    AuthenticatedAppSupplementsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdjustersRoute: typeof AuthenticatedAppAdjustersRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppCalendarRoute: typeof AuthenticatedAppCalendarRoute
  AuthenticatedAppClaimsRoute: typeof AuthenticatedAppClaimsRouteWithChildren
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppInterviewRoute: typeof AuthenticatedAppInterviewRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSupplementsRoute: typeof AuthenticatedAppSupplementsRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdjustersRoute: AuthenticatedAppAdjustersRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppCalendarRoute: AuthenticatedAppCalendarRoute,
  AuthenticatedAppClaimsRoute: AuthenticatedAppClaimsRouteWithChildren,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppInterviewRoute: AuthenticatedAppInterviewRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSupplementsRoute:
    AuthenticatedAppSupplementsRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAiExecutiveSummaryRoute: ApiAiExecutiveSummaryRoute,
  ApiAiInterviewSummaryRoute: ApiAiInterviewSummaryRoute,
  ApiAiSupplementGenerateRoute: ApiAiSupplementGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
